Category.create!(id:1, name:  "勉強法")
Category.create!(id:2, name:  "定跡")
Category.create!(id:3, name:  "プロ棋士")
Category.create!(id:4, name:  "プロの対局")
Category.create!(id:5, name:  "自分の対局")
Category.create!(id:6, name:  "その他")
